### ISSUE TITLE
Bug: `.. admonition::` directive is not layered properly

### ISSUE THREAD

**Issue by JacobCoffee** [lepture/shibuya#34]
Compared to all other builtin admonitions, `.. admonition::` seems to be rendering weirdly

<img width="66" alt="image" src="https://github.com/lepture/shibuya/assets/45884264/8f3e7e42-4ec2-47a3-9a6d-ba5e95f95218">

<img width="827" alt="image" src="https://github.com/lepture/shibuya/assets/45884264/8af05b09-b1aa-449f-b43a-696d66265120">

**Comment by lepture** [comment]
This is caused by your accent colors definition. Please check https://shibuya.lepture.com/writing/admonition/#generic-admonition

If you want to keep your accent colors, you can customize your css:

```css
.admonition {
    --icon-url: var(--i-bell-url);
    --color-1: var(--color-surface-accent);
    --color-2: var(--accent-a3);
    --color-3: var(--accent-9);
    --color-4: var(--accent-a11);
}
```

By replacing those accent colors.
