### ISSUE TITLE
Colors Documentation

### ISSUE THREAD

**Issue by JacobCoffee** [lepture/shibuya#5]
Hi, I'm not sure if I am dumb here but I'm seeing no changes when doing anything but the `conf.py` changes for the base theme color. I can edit these same variables in console and they change, I've tried hex colors, I've tried a few other things (I think, I'm not really a front end person so this is a bit lost on me).

Am I missing something here?

`docs/conf.py`
```py
html_css_files = [
    "custom.css",
]

html_theme_options = {
    "logo_target": "/",
    "announcement": "This documentation is currently under development.",
    "light_css_variables": {
        "--sy-rc-theme": "66, 177, 168",
    },
    "dark_css_variables": {
        "--sy-rc-theme": "66, 177, 168",
    },
}
```
`docs/_static/custom.css`
```css
html.light, html.dark {
    --sy-c-foot-bg: rgb(248, 56, 56);
    --sy-c-foot-divider: rgb(248, 56, 56);
    --sy-c-foot-text: rgb(248, 56, 56);
    --sy-c-bold: rgb(248, 56, 56);
    --sy-c-heading: rgb(248, 56, 56);
    --sy-c-text-weak: rgb(248, 56, 56);
    --sy-c-text: rgb(248, 56, 56);
    --sy-c-bg-weak: rgb(248, 56, 56);
    --sy-c-bg: rgb(248, 56, 56);
    --sy-rc-text: rgb(248, 56, 56);
    --sy-rc-invert: rgb(248, 56, 56);
    --sy-rc-bg: rgb(248, 56, 56);
    --sy-c-link: rgb(248, 56, 56);
}


html.light {
  --yue-c-text: #c722bf;
}

html.dark {
  --yue-c-text: #ff0606;
}
```
